### ISSUE TITLE
Upgrade breaks things

### ISSUE THREAD

**Issue by malle-pietje** [cnj-digital/seotamic#26]
Running Landtamic which come with SEOtamic 2. 

After purchasing a license and upgrading to beta 3 the SEO tags are no longer rendered. Any idea where to look? This looks quite messy...

**Comment by martink635** [comment]
Hello,
the v3 was in Beta. There was no migration script for older instalations up to this point. Please check out the readme for the v3, since there are some changes (hence a new major release)

Not sure what the exact issue is, are the tags not rendered in antlers? Are you having issues in the CP? Please use the migration script (backup before).

If you still have the same issue after migrating and updating to the 3.0.0 version (released right now) please reopen the issue.

Thanks!

**Comment by malle-pietje** [comment]
Thanks for the feedback, I hadn't checked out the new version 3.1. I've now installed that version and run the migration script.

Still the SEO tags are no longer rendered on the pages. Here's where the tags are added to the general page layout:
```html
    {{# Favicon #}}
    {{ partial:partials/favicons }}

    {{# SEO Meta Tags #}}
    {{ seotamic }}

    {{# Styling Tags #}}
    <link rel="stylesheet" href="{{ mix src='css/tailwind.css' }}" />
```
And this is the rendered HTML:
```html
<title></title>

<meta name="description" content="">

<link rel="stylesheet" href="/css/tailwind.css" />

```

**Comment by malle-pietje** [comment]
Also, after the upgrade I'm seeing this even though I have a license (even 2 IIRC) assigned to this site...
![image](https://user-images.githubusercontent.com/12016131/221584711-14e6ac3b-f434-40ea-b567-d7b21280fefc.png)

**Comment by malle-pietje** [comment]
Maybe I need to add that the initial install of Seotamic came with the Landtamic starterkit.

**Comment by malle-pietje** [comment]
@martink635 I can't seem to re-open the issue. You want me to create a new one?

**Comment by martink635** [comment]
@malle-pietje Can you share a minimum reproduction repo? If you can add me to the private/public repo as a collaborator that's fine as well. It's really hard to solve this without seeing the code

**Comment by malle-pietje** [comment]
I've been digging further and I believe the issue is caused by the fact that the migration script isn't cleaning up the blueprints.

After manually removing the SEO section, things are looking much better.

Here's the SEO section I removed from my posts blueprint:
```yaml

  SEO:
    display: SEO
    fields:
      -
        handle: seotamic_meta
        field:
          display: Meta
          listable: hidden
          type: section
          localizable: true
      -
        handle: seotamic_title
        field:
          options:
            title: Title
            custom: Custom
          clearable: false
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: true
          listable: hidden
          default: title
          display: Title
          instructions: 'It can be used to determine the title used on search engine results pages.'
      -
        handle: seotamic_custom_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: true
          listable: hidden
          display: 'Custom Meta Title'
          if:
            seotamic_title: 'equals custom'
      -
        handle: seotamic_title_prepend
        field:
          type: toggle
          instructions: 'Prepends to title the text set in General SEO settings'
          localizable: true
          default: true
          width: 50
          listable: hidden
          display: 'Title prepend'
      -
        handle: seotamic_title_append
        field:
          type: toggle
          localizable: true
          instructions: 'Appends to title the text set in General SEO settings'
          width: 50
          listable: hidden
          default: true
          display: 'Title append'
      -
        handle: seotamic_meta_description
        field:
          options:
            empty: Empty
            general: General
            custom: Custom
          clearable: false
          default: empty
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          instructions: 'It can be used to determine the text used under the title on search engine results pages. If empty, search engines will automatically generate this text.'
          localizable: true
          listable: hidden
          display: 'Meta description'
      -
        handle: seotamic_custom_meta_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: true
          listable: hidden
          display: 'Custom Meta description'
          if:
            seotamic_meta_description: 'equals custom'
      -
        handle: seotamic_canonical
        field:
          type: link
          instructions: 'By default it will be set to the page url'
          localizable: true
          listable: hidden
          display: Canonical
      -
        handle: seotamic_social
        field:
          type: section
          localizable: true
          listable: hidden
          display: Social
      -
        handle: seotamic_open_graph_title
        field:
          options:
            title: Title
            general: General
            custom: Custom
          clearable: false
          default: title
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: true
          listable: hidden
          display: 'Open Graph title'
      -
        handle: seotamic_custom_open_graph_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: true
          listable: hidden
          display: 'Custom Open Graph title'
          if:
            seotamic_open_graph_title: 'equals custom'
      -
        handle: seotamic_open_graph_description
        field:
          options:
            meta: 'Meta description'
            general: 'General description'
            custom: Custom
          clearable: false
          default: general
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: true
          listable: hidden
          display: 'Open Graph description'
      -
        handle: seotamic_custom_open_graph_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: true
          listable: hidden
          display: 'Custom Open Graph description'
          if:
            seotamic_open_graph_description: 'equals custom'
      -
        handle: seotamic_image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          instructions: "If not set, the general image will be used. It's best to use an image with a 1.91:1 aspect ratio that is at least 1200px wide for universal support. The image will be resized to 1200 width."
          localizable: true
          listable: hidden
          display: Image
      -
        handle: seotamic_twitter_title
        field:
          options:
            title: Title
            general: General
            custom: Custom
          clearable: false
          default: title
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: true
          listable: hidden
          display: 'Twitter title'
      -
        handle: seotamic_custom_twitter_title
        field:
          input_type: text
          character_limit: 100
          type: text
          localizable: true
          listable: hidden
          display: 'Custom Twitter title'
          if:
            seotamic_twitter_title: 'equals custom'
      -
        handle: seotamic_twitter_description
        field:
          options:
            meta: 'Meta description'
            general: 'General description'
            custom: Custom
          clearable: false
          default: general
          multiple: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          type: select
          localizable: true
          listable: hidden
          display: 'Twitter description'
      -
        handle: seotamic_custom_twitter_description
        field:
          input_type: text
          character_limit: 200
          type: textarea
          localizable: true
          listable: hidden
          display: 'Custom Twitter description'
          if:
            seotamic_twitter_description: 'equals custom'
```
